Fix pipeline
FGA-DIKU/EHR pull request #10
Opened 2024-08-12 14:17 UTC by kirilklein

The full pipeline is working now. 

Summary of the changes:
1.  Data Creation
     - Bg and death were previously removed
2. Outcome creation 
     - Minor bug fixes 
4. Finetuning
      - Fixes related to model, mostly attention mask which is now constructed on the fly in the dataset
      - trainer had to be fixed, previous changes messed up evaluation
      - fine-tuning script was restructured

2024-08-13 09:07 UTC, kirilklein commented on corebehrt/classes/features.py
Otherwise TIMESTAMP and ADMISSION_ID values are None and the nan filter which is the next step drops death and bg

2024-08-13 09:09 UTC, kirilklein commented on corebehrt/data/filter.py
We can keep it for now. Later we will have all the data in one table and filtering will be more straightforward

2024-08-13 09:10 UTC, kirilklein commented on corebehrt/data/utils.py
the previos version resulted in an error

2024-08-13 09:11 UTC, kirilklein commented on corebehrt/data_fixes/censor.py
Removed attention mask, since at data preparation we have the unpadded sequence and the attention mask are just ones

2024-08-13 09:12 UTC, kirilklein commented on corebehrt/evaluation/metrics.py
didn't produce a full cm f targets and predictions have only one class

2024-08-13 09:14 UTC, kirilklein commented on corebehrt/main/finetune_cv.py
Put code into main function. This currently requires to pass a lot of arguments around, so should be improved

2024-08-19 17:38 UTC, StephanLorenzen commented on corebehrt/classes/features.py
I see. Currently we also drop them in main/create_data.py (l: 169), but after the excluder. So we should do it only one place, either here, or move it in main/create_data.py to be before the excluder.

2024-08-20 08:16 UTC, StephanLorenzen requested changes
Its good!

My main confusion right now is how to actually run the pipeline. I set up the first step to be run as `python -m corebehrt.main.create_data` from the repo root dir, but this no longer works.

Can you remove it from the README, and add instructions for how to run the pipeline?

2024-08-23 08:09 UTC, StephanLorenzen approved these changes

2024-08-23 08:10 UTC, merged