Test setup
FGA-DIKU/EHR pull request #6
Opened 2024-07-23 12:14 UTC by StephanLorenzen

* Added tests from features branch for corebehrt.functional
* Added tests from features branch for corebehrt.classes
* Updated README
* Created requirements file with pipreqs.

2024-07-23 13:23 UTC, mikkelfo requested changes

2024-07-24 08:00 UTC, StephanLorenzen commented on tests/test_features.py
> +)  # Replace 'your_module' with the actual module name
Removed.

2024-07-24 08:09 UTC, StephanLorenzen commented on tests/test_creators.py
Yeah, that was left in by mistake, at it is empty (all tests are commented). I added tests for functional.creators instead.

Two test differs from the previous test (which were commented):
* `create_segments` creates 0-indexed segments (before they were 1-indexed), so the output becomes [0,0,0,1] instead of [1,1,1,2]
* `create_ages` creates floating point ages (compared to the old BaseCreator, which outputted ints, I think). These fps are slightly off. The test passes using round, but we probably need to define, what `create_ages` should return and then update the test.

2024-07-24 08:10 UTC, StephanLorenzen commented on tests/test_creators.py
Both functions seems to be used directly in main_create_data without "fixing" the output. It probably does not matter for create_segments, but ages may change the downstream outputs slightly.

2024-07-24 09:36 UTC, mikkelfo commented on tests/test_creators.py
> Yeah, that was left in by mistake, at it is empty (all tests are commented). I added tests for functional.creators instead.
> 
> Two test differs from the previous test (which were commented):
> 
> * `create_segments` creates 0-indexed segments (before they were 1-indexed), so the output becomes [0,0,0,1] instead of [1,1,1,2]

0-indexed segments are correct now, as we create the background before computing segments, where we did it after in the old code and manually set segment=0 for background.

> * `create_ages` creates floating point ages (compared to the old BaseCreator, which outputted ints, I think). These fps are slightly off. The test passes using round, but we probably need to define, what `create_ages` should return and then update the test.

`create_ages` should output floating point ages now, as we use time2vec by default (old code used `nn.Embedding` and needed ints)

2024-07-24 09:38 UTC, mikkelfo approved these changes

2024-07-24 09:39 UTC, merged